import { Response } from 'express';
import { AuthenticatedRequest } from '../middleware/authMiddleware';
import { DBEngine } from '../db/db';
import { NotificationService } from '../db/mongodb';

export class StatsController {
  static async getStats(req: AuthenticatedRequest, res: Response): Promise<void> {
    try {
      const users = DBEngine.getUsers();
      const hostels = DBEngine.getHostels();
      const rooms = DBEngine.getRooms();
      const applications = DBEngine.getApplications();

      // Counts
      const totalStudents = users.filter(u => u.role === 'student').length;
      const totalHostels = hostels.length;
      const totalRooms = rooms.length;
      const totalApplications = applications.length;
      const pendingApplications = applications.filter(a => a.status === 'pending').length;
      
      const totalCapacity = rooms.reduce((sum, r) => sum + r.capacity, 0);
      const allocatedRooms = rooms.reduce((sum, r) => sum + r.occupied, 0);
      const occupancyRate = totalCapacity > 0 ? Math.round((allocatedRooms / totalCapacity) * 100) : 0;

      // Charts data 1: Hostel Allocation Status (Capacity vs Occupied)
      const hostelCapacityChart = hostels.map(h => {
        const hostelRooms = rooms.filter(r => r.hostelId === h.id);
        const capacity = hostelRooms.reduce((sum, r) => sum + r.capacity, 0);
        const occupied = hostelRooms.reduce((sum, r) => sum + r.occupied, 0);
        return {
          name: h.name,
          capacity,
          occupied,
          available: capacity - occupied,
        };
      });

      // Charts data 2: Applications by Status
      const pendingCount = applications.filter(a => a.status === 'pending').length;
      const approvedCount = applications.filter(a => a.status === 'approved').length;
      const rejectedCount = applications.filter(a => a.status === 'rejected').length;
      const applicationStatusChart = [
        { name: 'Pending', value: pendingCount, color: '#f59e0b' },
        { name: 'Approved', value: approvedCount, color: '#10b981' },
        { name: 'Rejected', value: rejectedCount, color: '#ef4444' },
      ];

      // Charts data 3: Applications Gender Distribution
      const maleApps = applications.filter(a => {
        const stud = users.find(u => u.id === a.studentId);
        return stud?.gender === 'male';
      }).length;
      const femaleApps = applications.filter(a => {
        const stud = users.find(u => u.id === a.studentId);
        return stud?.gender === 'female';
      }).length;
      const genderDistributionChart = [
        { name: 'Male Applicants', value: maleApps },
        { name: 'Female Applicants', value: femaleApps },
      ];

      // Charts data 4: Revenue generated by paid rooms
      const revenueByHostel = hostels.map(h => {
        const hostelRooms = rooms.filter(r => r.hostelId === h.id);
        const revenue = hostelRooms.reduce((sum, r) => sum + (r.occupied * r.price), 0);
        return {
          name: h.name,
          revenue,
        };
      });

      res.status(200).json({
        summary: {
          totalStudents,
          totalHostels,
          totalRooms,
          totalApplications,
          pendingApplications,
          allocatedRooms,
          occupancyRate,
          totalCapacity,
        },
        charts: {
          hostelCapacity: hostelCapacityChart,
          applicationStatus: applicationStatusChart,
          genderDistribution: genderDistributionChart,
          revenue: revenueByHostel,
        }
      });
    } catch (error: any) {
      console.error('Error computing dashboard statistics:', error);
      res.status(500).json({ error: 'Failed to compute dashboard statistics.' });
    }
  }

  static async getDetailedAnalytics(req: AuthenticatedRequest, res: Response): Promise<void> {
    try {
      const users = DBEngine.getUsers();
      const hostels = DBEngine.getHostels();
      const rooms = DBEngine.getRooms();
      const applications = DBEngine.getApplications();

      // Basic Counts
      const totalStudents = users.filter(u => u.role === 'student').length;
      const totalHostels = hostels.length;
      const totalRooms = rooms.length;
      const totalCapacity = rooms.reduce((sum, r) => sum + r.capacity, 0);
      const allocatedBeds = rooms.reduce((sum, r) => sum + r.occupied, 0);
      const vacantBeds = Math.max(0, totalCapacity - allocatedBeds);
      const occupancyRate = totalCapacity > 0 ? Math.round((allocatedBeds / totalCapacity) * 100) : 0;

      // Revenue computations
      // Realized Revenue: Approved + Paid applications
      let realizedRevenue = 0;
      applications.forEach(app => {
        if (app.status === 'approved' && app.paymentStatus === 'paid') {
          const room = rooms.find(r => r.id === app.roomId);
          realizedRevenue += room ? room.price : 0;
        }
      });

      // Projected Revenue: All occupied slots in rooms
      const projectedRevenue = rooms.reduce((sum, r) => sum + (r.occupied * r.price), 0);

      // 1. Occupancy Breakdown by Hostel
      const occupancyByHostel = hostels.map(h => {
        const hostelRooms = rooms.filter(r => r.hostelId === h.id);
        const capacity = hostelRooms.reduce((sum, r) => sum + r.capacity, 0);
        const occupied = hostelRooms.reduce((sum, r) => sum + r.occupied, 0);
        const available = Math.max(0, capacity - occupied);
        const rate = capacity > 0 ? Math.round((occupied / capacity) * 100) : 0;
        return {
          id: h.id,
          name: h.name,
          type: h.type,
          capacity,
          occupied,
          available,
          occupancyRate: rate,
          status: rate >= 90 ? 'Full' : rate <= 30 ? 'Low' : 'Stable'
        };
      });

      // 2. Occupancy by Room Type
      // Let's group rooms by capacity: 1=Single, 2=Double, 4=Quad, others=Multi
      const roomGroups = {
        single: { name: 'Single Bed Room', capacityVal: 1, totalRooms: 0, capacity: 0, occupied: 0 },
        double: { name: 'Double Beds Room', capacityVal: 2, totalRooms: 0, capacity: 0, occupied: 0 },
        quad: { name: '4-In-1 Quad Room', capacityVal: 4, totalRooms: 0, capacity: 0, occupied: 0 },
        multi: { name: '6-In-1 Multi Room', capacityVal: 6, totalRooms: 0, capacity: 0, occupied: 0 }
      };

      rooms.forEach(r => {
        let grp = roomGroups.multi;
        if (r.capacity === 1) grp = roomGroups.single;
        else if (r.capacity === 2) grp = roomGroups.double;
        else if (r.capacity === 4) grp = roomGroups.quad;

        grp.totalRooms += 1;
        grp.capacity += r.capacity;
        grp.occupied += r.occupied;
      });

      const occupancyByRoomType = Object.values(roomGroups).map(g => ({
        roomType: g.name,
        capacityValue: g.capacityVal,
        totalRooms: g.totalRooms,
        totalCapacity: g.capacity,
        occupiedBeds: g.occupied,
        vacantBeds: Math.max(0, g.capacity - g.occupied),
        utilization: g.capacity > 0 ? Math.round((g.occupied / g.capacity) * 100) : 0
      }));

      // 3. Application Statistics
      const pendingApps = applications.filter(a => a.status === 'pending').length;
      const approvedApps = applications.filter(a => a.status === 'approved').length;
      const rejectedApps = applications.filter(a => a.status === 'rejected').length;
      const totalApps = applications.length;

      // Application trend over last 6 months
      const last6Months: { monthId: string; monthName: string }[] = [];
      const now = new Date();
      for (let i = 5; i >= 0; i--) {
        const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
        const year = d.getFullYear();
        const month = String(d.getMonth() + 1).padStart(2, '0');
        const monthId = `${year}-${month}`;
        const monthName = d.toLocaleString('default', { month: 'short', year: 'numeric' });
        last6Months.push({ monthId, monthName });
      }

      const applicationTrends = last6Months.map(m => {
        const appsInMonth = applications.filter(a => a.createdAt.startsWith(m.monthId));
        return {
          month: m.monthName,
          submitted: appsInMonth.length,
          approved: appsInMonth.filter(a => a.status === 'approved').length,
          rejected: appsInMonth.filter(a => a.status === 'rejected').length
        };
      });

      // 4. Hostel Utilization Index
      let highlyUtilized = 0;
      let moderatelyUtilized = 0;
      let underUtilized = 0;

      occupancyByHostel.forEach(h => {
        if (h.capacity === 0) return;
        const rate = h.occupancyRate;
        if (rate > 80) highlyUtilized++;
        else if (rate >= 40) moderatelyUtilized++;
        else underUtilized++;
      });

      const hostelUtilization = {
        totalHostels,
        highlyUtilized,
        moderatelyUtilized,
        underUtilized,
        byGender: {
          male: {
            capacity: occupancyByHostel.filter(h => h.type === 'male').reduce((s, h) => s + h.capacity, 0),
            occupied: occupancyByHostel.filter(h => h.type === 'male').reduce((s, h) => s + h.occupied, 0)
          },
          female: {
            capacity: occupancyByHostel.filter(h => h.type === 'female').reduce((s, h) => s + h.capacity, 0),
            occupied: occupancyByHostel.filter(h => h.type === 'female').reduce((s, h) => s + h.occupied, 0)
          }
        }
      };

      // 5. Student Statistics
      const studentUsers = users.filter(u => u.role === 'student');
      const maleStudentsCount = studentUsers.filter(u => u.gender === 'male').length;
      const femaleStudentsCount = studentUsers.filter(u => u.gender === 'female').length;
      const otherStudentsCount = studentUsers.filter(u => u.gender !== 'male' && u.gender !== 'female').length;

      // Group students by department
      const departmentCounts: Record<string, number> = {};
      studentUsers.forEach(s => {
        const dept = s.department || 'Not Specified';
        departmentCounts[dept] = (departmentCounts[dept] || 0) + 1;
      });

      const studentByDepartment = Object.entries(departmentCounts).map(([name, count]) => ({
        name,
        count
      })).sort((a, b) => b.count - a.count);

      // Student allocation status
      const studentAllocated = studentUsers.filter(s => {
        return applications.some(a => a.studentId === s.id && a.status === 'approved' && a.paymentStatus === 'paid');
      }).length;

      const studentPending = studentUsers.filter(s => {
        const hasApprovedPaid = applications.some(a => a.studentId === s.id && a.status === 'approved' && a.paymentStatus === 'paid');
        if (hasApprovedPaid) return false;
        return applications.some(a => a.studentId === s.id && (a.status === 'pending' || (a.status === 'approved' && a.paymentStatus === 'unpaid')));
      }).length;

      const studentUnapplied = Math.max(0, totalStudents - studentAllocated - studentPending);

      const studentStats = {
        total: totalStudents,
        genderDistribution: [
          { name: 'Male', value: maleStudentsCount },
          { name: 'Female', value: femaleStudentsCount },
          { name: 'Other', value: otherStudentsCount }
        ],
        byDepartment: studentByDepartment,
        allocationStatus: [
          { name: 'Secured Slot', value: studentAllocated, color: '#10b981' },
          { name: 'Pending Allocation', value: studentPending, color: '#f59e0b' },
          { name: 'Unapplied', value: studentUnapplied, color: '#64748b' }
        ]
      };

      // 6. Monthly Reports list
      const monthlyReports = last6Months.map(m => {
        const monthApps = applications.filter(a => a.createdAt.startsWith(m.monthId));
        const approvedInMonth = monthApps.filter(a => a.status === 'approved');
        const paidInMonth = monthApps.filter(a => a.paymentStatus === 'paid');

        // Revenue in month
        const revenue = paidInMonth.reduce((sum, app) => {
          const room = rooms.find(r => r.id === app.roomId);
          return sum + (room ? room.price : 0);
        }, 0);

        // Find most popular hostel in month
        const hostelAppCounts: Record<string, number> = {};
        monthApps.forEach(a => {
          hostelAppCounts[a.hostelId] = (hostelAppCounts[a.hostelId] || 0) + 1;
        });

        let topHostelName = 'No Applications';
        let maxCount = 0;
        Object.entries(hostelAppCounts).forEach(([hId, count]) => {
          if (count > maxCount) {
            maxCount = count;
            const h = hostels.find(hostel => hostel.id === hId);
            if (h) topHostelName = h.name;
          }
        });

        return {
          monthId: m.monthId,
          monthName: m.monthName,
          newApplicationsCount: monthApps.length,
          approvedApplicationsCount: approvedInMonth.length,
          paymentsConfirmedCount: paidInMonth.length,
          revenueGenerated: revenue,
          topHostelName
        };
      }).reverse(); // Latest month first

      res.status(200).json({
        summary: {
          totalStudents,
          totalHostels,
          totalRooms,
          totalCapacity,
          allocatedBeds,
          vacantBeds,
          occupancyRate,
          realizedRevenue,
          projectedRevenue
        },
        occupancy: {
          byHostel: occupancyByHostel,
          byRoomType: occupancyByRoomType
        },
        applications: {
          byStatus: {
            pending: pendingApps,
            approved: approvedApps,
            rejected: rejectedApps,
            total: totalApps
          },
          trends: applicationTrends
        },
        hostelUtilization,
        studentStats,
        monthlyReports
      });
    } catch (error: any) {
      console.error('Error generating advanced admin analytics:', error);
      res.status(500).json({ error: 'Failed to generate advanced admin analytics.' });
    }
  }

  static async getNotifications(req: AuthenticatedRequest, res: Response): Promise<void> {
    try {
      const user = req.user;
      const notifs = await NotificationService.getNotificationsForUser(user.id, user.role);
      res.status(200).json(notifs);
    } catch (error: any) {
      console.error('Error fetching notifications:', error);
      res.status(500).json({ error: 'Failed to fetch user notifications.' });
    }
  }

  static async markNotificationRead(req: AuthenticatedRequest, res: Response): Promise<void> {
    try {
      const { id } = req.params;
      const user = req.user;
      const success = await NotificationService.markAsRead(id, user.id);
      if (!success) {
        res.status(404).json({ error: 'Notification not found.' });
        return;
      }
      res.status(200).json({ message: 'Notification marked as read.' });
    } catch (error: any) {
      console.error('Error marking notification read:', error);
      res.status(500).json({ error: 'Failed to update notification status.' });
    }
  }

  static async createAnnouncement(req: AuthenticatedRequest, res: Response): Promise<void> {
    try {
      const { title, message } = req.body;
      if (!title || !message) {
        res.status(400).json({ error: 'Title and message are required for system announcements.' });
        return;
      }

      const announcement = await NotificationService.createNotification(
        'all',
        title,
        message,
        'system_announcement'
      );

      res.status(201).json({
        message: 'System announcement broadcast successfully.',
        announcement
      });
    } catch (error: any) {
      console.error('Error creating system announcement:', error);
      res.status(500).json({ error: 'Failed to broadcast system announcement.' });
    }
  }

  static async listStudents(req: AuthenticatedRequest, res: Response): Promise<void> {
    try {
      const users = DBEngine.getUsers();
      let students = users.filter(u => u.role === 'student');

      const { search, department, page, limit } = req.query;

      if (search) {
        const searchStr = String(search).toLowerCase();
        students = students.filter(
          s => s.name.toLowerCase().includes(searchStr) || 
               s.email.toLowerCase().includes(searchStr) || 
               (s.matricNoOrStaffId && s.matricNoOrStaffId.toLowerCase().includes(searchStr))
        );
      }

      if (department && department !== 'all') {
        const deptStr = String(department).toLowerCase();
        students = students.filter(s => s.department && s.department.toLowerCase() === deptStr);
      }

      const totalCount = students.length;

      if (page && limit) {
        const pageNum = Math.max(1, Number(page));
        const limitNum = Math.max(1, Number(limit));
        const startIndex = (pageNum - 1) * limitNum;
        const endIndex = pageNum * limitNum;

        const paginatedStudents = students.slice(startIndex, endIndex);

        res.setHeader('X-Total-Count', totalCount.toString());
        res.setHeader('X-Page', pageNum.toString());
        res.setHeader('X-Limit', limitNum.toString());
        res.setHeader('X-Total-Pages', Math.ceil(totalCount / limitNum).toString());

        res.status(200).json(paginatedStudents);
        return;
      }

      res.status(200).json(students);
    } catch (error: any) {
      console.error('Error retrieving students directory:', error);
      res.status(500).json({ error: 'Failed to fetch students listing.' });
    }
  }
}
